# Generated by Django 4.1.4 on 2023-01-06 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='l',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='m',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store_app.product'),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='s',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='xl',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='xs',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='xxl',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='xxxl',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
