# Generated by Django 4.1.4 on 2023-01-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0003_alter_sizes_l_alter_sizes_m_alter_sizes_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizes',
            name='l',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='m',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='s',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='xl',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='xs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='xxl',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='xxxl',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
