# Generated by Django 4.1.4 on 2023-01-07 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_alter_sizes_l_alter_sizes_m_alter_sizes_s_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-is_main', 'pk']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
