# Generated by Django 4.1.4 on 2023-01-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_neighborhood_alter_order_street_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dni',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
