# Generated by Django 4.1.4 on 2023-01-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zip_code',
            field=models.CharField(default=3432, max_length=10),
            preserve_default=False,
        ),
    ]
