# Generated by Django 4.1.4 on 2023-01-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_status_order_shipping_status_order_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.CharField(default='', max_length=550),
        ),
    ]
